[package]
name = "whatsong"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[[bin]]
name = "whatsong_client"
path = "src/bin/client.rs"

[[bin]]
name = "whatsong_server"
path = "src/bin/server.rs"

[[bin]]
name = "whatsong_bot"
path = "src/bin/bot.rs"

[dependencies]
log = "0.4.6"
flexi_logger = "0.13.2"

ctrlc = "3.1.3"
regex = "1.1.6"
once_cell = "0.2.1"

toml = { version = "0.5.1", features = ["preserve_order"] }

directories = "2.0.1"
twitchchat = "0.6.1"

serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"

attohttpc = { version = "0.4.1", features = ["json"] }
tiny_http = "0.6.2"

rusqlite = { version = "0.18.0", features = ["bundled"] }
chrono = "0.4.6"

[patch.crates-io]
tiny_http = { git = "https://github.com/museun/tiny-http" }
