[package]
name = "whatsong"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[[bin]]
name = "whatsong_client"
path = "src/bin/client.rs"

[[bin]]
name = "whatsong_server"
path = "src/bin/server.rs"

[[bin]]
name = "whatsong_bot"
path = "src/bin/bot.rs"

[dependencies]
log = "0.4.8"
flexi_logger = "0.14.4"

ctrlc = "3.1.3"
regex = "1.3.1"
once_cell = "1.2.0"

toml = { version = "0.5.3", features = ["preserve_order"] }

directories = "2.0.2"
twitchchat = "0.7.2"

serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"

attohttpc = { version = "0.4.5", features = ["json"] }
tiny_http = "0.6.2"

rusqlite = { version = "0.20.0", features = ["bundled"] }
chrono = "0.4.9"

[patch.crates-io]
tiny_http = { git = "https://github.com/museun/tiny-http" }
